const productsNew = [
    {
        productId: 1,
        productImage: 'src="image/catalog_img_6.png"',
        productName: "ELLERY X M'O CAPSULE",
        productDiscription: 'Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.',
        productSize: '',
        productPrice: '$52.00',
        productBrand: '',
        productCategory: '',
    },
    {
        productId: 2,
        productImage: 'image/catalog_img_2.png',
        productName: '',
        productDiscription: '',
        productSize: '',
        productPrice: '',
        productBrand: '',
        productCategory: '',
    },
    {
        productId: 3,
        productImage: 'image/catalog_img_3.png',
        productName: '',
        productDiscription: '',
        productSize: '',
        productPrice: '',
        productBrand: '',
        productCategory: '',
    },
    {
        productId: 4,
        productImage: 'image/catalog_img_4.png',
        productName: '',
        productDiscription: '',
        productSize: '',
        productPrice: '',
        productBrand: '',
        productCategory: '',
    },
    {
        productId: 5,
        productImage: 'image/catalog_img_5.png',
        productName: '',
        productDiscription: '',
        productSize: '',
        productPrice: '',
        productBrand: '',
        productCategory: '',
    },
    {
        productId: 6,
        productImage: 'image/catalog_img_6.png',
        productName: '',
        productDiscription: '',
        productSize: '',
        productPrice: '',
        productBrand: '',
        productCategory: '',
    },
    {
        productId: 7,
        productImage: 'image/catalog_img_7.png',
        productName: '',
        productDiscription: '',
        productSize: '',
        productPrice: '',
        productBrand: '',
        productCategory: '',
    },
    {
        productId: 8,
        productImage: 'image/catalog_img_8.png',
        productName: '',
        productDiscription: '',
        productSize: '',
        productPrice: '',
        productBrand: '',
        productCategory: '',
    },
    {
        productId: 9,
        productImage: 'image/catalog_img_9.png',
        productName: '',
        productDiscription: '',
        productSize: '',
        productPrice: '',
        productBrand: '',
        productCategory: '',
    }
];